### PR TITLE
Custom prefix support and opengl linking(mingw) fix in cmake

### PR DESCRIPTION
**Pull request by wirx6**

### CODE REVIEW

**Comment by wang-bin** [comment]
QtAV headers and libs should be installed to the same dir as Qt. At least it should be the default if CMAKE_INSTALL_PREFIX is not set

**Comment by wang-bin** [comment]
since qt5.5, you don't need to link to opengl because dynamic opengl is the default. what's your qt version?

**Comment by wirx6** [comment]
I have qt5.8 but on MinGW need to link opengl, if it isn't needed linker will strip this anyway.
Custom prefix is required in majority of package build systems like PKGBUILD.

**Comment by wirx6** [comment]
Btw I wrote a PKGBUILD for MSYS2 #533 but it requires this patch
[a.zip](https://github.com/wang-bin/QtAV/files/749048/a.zip)

**Comment by wang-bin** [comment]
> I have qt5.8 but on MinGW need to link opengl
I will try the next week. I have enough disk space now.

> Custom prefix is required in majority of package build systems like PKGBUILD
What if there are 2 versions of Qt? We can not install to the same prefix. So your patch should use a default path if prefix is not set. The default path is Qt files' dir.

**Comment by wang-bin** [comment]
`${QT_INSTALL_PREFIX}/lib` and `${QT_INSTALL_LIBS}` are not identical. For example, on linux, QT_INSTALL_PREFIX can be /usr, but QT_INSTALL_LIBS is /usr/lib/x86_64-linux-gnu, QT_INSTALL_HEADERS is /usr/include/x86_64-linux-gnu/qt5. So you have to add more vars, such as QTAV_INSTALL_HEADERS, QTAV_INSTALL_LIBS, set the default value to QT_INSTALL_HEADERS and QT_INSTALL_LIBS, and change to CMAKE_INSTALL_PREFIX/include or lib if specified by user.

**Comment by wang-bin** [comment]
btw, remove your opengl patch because it is fixed in the latest code. And it's better to merge all your commits into 1

**Comment by wang-bin** [comment]
LGTM. Thanks.

**Pull request merged**
