### PR TITLE
Adding the possibility to change the bg color for the WidgetRenderer

### PR DESCRIPTION
**Pull request by agudpp**
small change to let the user set the bg color of the WidgetRenderer

### CODE REVIEW

**Comment by wang-bin** [comment]
I'd like to add it in VideoRenderer instead of WidgetRenderer. You can have a try.

**Comment by agudpp** [comment]
hi @wang-bin , sorry the delay, ok, so the plan is to paint the "VideoFrame" instead of the widget?

**Comment by wang-bin** [comment]
Background color is easy in all graphics apis. So adding the property in `VideoRenderer` is fine

**Comment by agudpp** [comment]
you mean move up the m_bgColor to VideoRender but not the code of filling the background? I though u mean move the logic as well to the parent class.
I will move the api up.

**Comment by wang-bin** [comment]
yes

**Comment by agudpp** [comment]
@wang-bing let me try one thing more before moving forward. I sadly didn't have enough time for this. I will check it next week.

**Comment by wang-bin** [comment]
Looks good.
You'd better to use `git rebase upstream/master` instead of `git merge upstream/master` in your branch to avoid additional commit like `Merge branch 'master' into`

**Comment by agudpp** [comment]
:+1:  thanks for the tip! good.

**Comment by jlinse** [comment]
Wow, I just added the same functionality into my branch for the QuickFBORenderer.  Wish I looked here first.  It looks like your doing a bit more work when you set the background color in VideoRenderer.  I wasn't sure if we should be doing that there or if it should be taken care of in the particular renderer itself.  Either way if you want to look at my patch for for Background Color support for QuickFBORendering and QML Video.
My diff is https://github.com/jlinse/QtAV/commit/20fd4c14e6e53ca26359f7e15c2971d67114860f

**Comment by wang-bin** [comment]
@jlinse looks good

**Comment by wang-bin** [comment]
done in 1a970d94a0a9e

**Pull request closed without merging**
