### PR TITLE
Fix STATICLINK for iOS

### PR DESCRIPTION
**Pull request by correa**
Fix STATICLINK for ios and other platforms that use staticlib by default in their mkspecs

Signed-off-by: Thiago A. Correa <thiago.correa@gmail.com>

### CODE REVIEW

**Comment by wang-bin** [comment]
seems good. why did you close it? btw, I think `STATICLINK` is not necessary and can be replaced with staticlib

**Comment by correa** [comment]
I had problems with the new widgets library and was trying to figure it
out. I can't build it because of missing symbols in ffmpeg as it seems.

**Comment by correa** [comment]
I will resend a better version. Works on Win32 but having problems linking against ffmpeg for ios, it misses iconv and some other references. Looks like it's unrelated to my changes, but not sure.

**Comment by wang-bin** [comment]
I can build QtAV for ios simulator. The command I used to build ffmpeg is from here: https://github.com/FFmpeg/gas-preprocessor

**Pull request closed without merging**
